USE [Prueba]
GO

/****** Object:  StoredProcedure [dbo].[sp_UpdateGiros]    Script Date: 27/05/2022 3:09:57 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[sp_UpdateGiros]
	@GIR_GIRO_ID int,
	@GIR_RECIBO nvarchar(100),
	@GIR_CIUDAD_ID int
AS
BEGIN
	IF EXISTS (SELECT GIR_GIRO_ID FROM dbo.GIROS WHERE GIR_GIRO_ID = @GIR_GIRO_ID)
	BEGIN
		UPDATE dbo.GIROS
		SET GIR_RECIBO=@GIR_RECIBO, GIR_CIUDAD_ID = @GIR_CIUDAD_ID
		WHERE GIR_GIRO_ID = @GIR_GIRO_ID
		SELECT 1
	END
	ELSE
	BEGIN
		SELECT 0
	END
END
GO

